### ISSUE TITLE
Norwegian characters encoding

### ISSUE THREAD

**Issue by stianlp** [greengerong/prerender-java#30]
I have the same as @lukezheng posted here https://github.com/greengerong/prerender-java/issues/13. Because it's closed created a new issue.

The problem is with Norwegian characters (æ,ø,å).

See the ø in Hønefoss:
http://www.snapsale.com/?_escaped_fragment_=/browse/4692794220216320

From prerender servers it's correct:
http://service.prerender.io/http://www.snapsale.com/?_escaped_fragment_=/browse/4692794220216320

Does anyone know what the problem might be?

**Comment by geirke** [comment]
@greengerong @stianlp The issue seems to be with the encoding of the request body. The headers are copied correctly from the proxy response, but the actual stream of characters written to the response is written with the default encoding instead of the encoding used by the proxy response. I have created a pull request that fixes the issue.

**Comment by greengerong** [comment]
merged. Thanks, everyone.
