### ISSUE TITLE
Issue with Cloud Foundry and Spring Boot

### ISSUE THREAD

**Issue by gerbsen** [greengerong/prerender-java#40]
Hey,
we have application which is deployed to cloud foundry and we use this plugin. The problem now is, that the prerender server get's wrong URLs to render:

Instead of: 
    https://xxxx.cfapps.io/#!/action/?param1=1&param2=2
I only see:
    https:/xxxx.cfapps.io/dist/index.html?param1=1&param2=2

We initialize the service as follows:

```
 private void initPrerender(ServletContext servletContext, EnumSet<DispatcherType> disps) {
    servletContext.addFilter("prerender", PreRenderSEOFilter.class); 
    servletContext.getFilterRegistration("prerender").setInitParameter("prerenderServiceUrl", "http://ip.for.the.server/prerender/");
    servletContext.getFilterRegistration("prerender").addMappingForUrlPatterns(disps, true, "/*");
}
```

What are we doing wrong?

Cheers,
Daniel

**Comment by thoop** [comment]
Is the `https:/` a typo or are you really only seeing a single `/` there?

The `dist/index.html` in the URL could be caused by your stack. Are you testing the URL as:

https://xxxx.cfapps.io/?_escaped_fragment_=/action/?param1=1&param2=2

If you are going to that URL and seeing the `/dist/index.html` URL, I'd think that your Prerender server is accessing:

https://xxxx.cfapps.io/?param1=1&param2=2#!/action/

Which is why, after your stack is adding the `dist/index.html`, you're seeing that URL being accessed.

**Comment by greengerong** [comment]
Maybe some SPA html5 history url?

**Comment by gerbsen** [comment]
Sorry.. I can't remember what actually was the issue. But we don't have it anymore.
