### ISSUE TITLE
PrerenderSeoService does not honor whitelist

### ISSUE THREAD

**Issue by codetothepoint** [greengerong/prerender-java#46]
I am trying to prerender pages based on URLs in a whitelist regardless of User-Agent.

`PrerenderSeoService` does not properly honor the whitelist configuration.  Lines 111 to 114 of `PrerenderSeoService` are currently:

``` 
if (whiteList != null && !isInWhiteList(url, whiteList)) {
    log.trace("Whitelist is enabled, but this request is not listed; intercept: no");
    return false;
}
...
```

Nowhere is `true` explicitly returned if a given URL appears in the whitelist.  Instead, the remaining checks are run and my URLs are being improperly captured by `if (!isInSearchUserAgent(userAgent))` (because I am trying to capture URLs by a whitelist instead of by a search bot User-Agent.)

The logic should be partially flipped to return `true` and prevent any remaining checks:

```
if (whiteList != null && isInWhiteList(url, whiteList)) {
    log.trace("Whitelist is enabled, and this request is listed; intercept: yes");
    return true;
}
...
```

The above would short-circuit the remaining checks and return `true` as expected regardless of User-Agent

**Comment by codetothepoint** [comment]
A suggested solution, proposed by @greengerong, would be to introduce a new flag to suppress User-Agent checking.  Adding a whitelist and suppressing User-Agent checking would resolve the use case outlined above.

**Comment by thoop** [comment]
The current implementation of the whitelist is correct. It should always still run the user agent check after the code has determined that the URL passes the whitelist check.

What is your use case for suppressing user agent checking? We don't recommend serving Prerendered pages to users when using our prerendering service since we remove javascript tags to prevent crawlers from trying to execute the javascript and clearing out the static html that has been prerendered.

**Comment by thoop** [comment]
Happy to help!

The problem here is the Prerender server will load all requests for a page, so it can take at least a few seconds to render the page in the best case scenario. That means your users could see a really slow page load when they could be rendering the javascript themselves much faster in their browser.

Also, if you leave the`<script>` tags on the page, the browser will run those script tags which will most likely just clear out the <html> app root and start again from nothing. So your users would see a flash of the prerendered page and then it could disappear while their browser tried to re-execute the javascript.

So if you are looking for real server-side rendering, you'll want to use a product that serializes the state when rendered on the server side and passes that state to be deserialized on the client side instead of re-rendering the page from scratch. That's a little more baked into SSR with frameworks Angular and React. And that's the reason why we only suggest serving prerendered pages to the crawlers if using our Prerender server. The crawlers don't need the javascript since they don't interact with the page, they just read the html.

Let me know if you have any questions about that.

**Comment by thoop** [comment]
You can preserve the `<script>` tags if you run your own prerender server and just don't add the plugin in `server.js` to remove script tags. Removing the script tags is optional when running your own prerender server.

That being said, this middleware repo is meant to be a drop-in config for use with https://prerender.io and our hosted service which removes `<script>` tags from the page to serve to the crawlers. So ideally this repo would stay that way. If you are able to fork this repo and add your change for your specific use case, I think that's the best way forward.
